### ISSUE TITLE
Update versions.

### ISSUE THREAD

**Issue by tomchristie** [tomchristie/django-vanilla-views#38]
* Update tests to include 1.8 (and ideally master, too).
* Update index page.
* Update docs pages.

**Comment by auvipy** [comment]
:+1:

**Comment by tomchristie** [comment]
@auvipy If you're feeling proactive then any pull requests for this would be most welcome! :smile:

**Comment by auvipy** [comment]
for the pointed tasks I have to update the tox.ini? run the tests localy with django 1.8 and update the docs to 1.8 right?

**Comment by tomchristie** [comment]
The tox.ini and the .travis.yml

**Comment by auvipy** [comment]
#47
