### ISSUE TITLE
Add `verbose_name` and `verbose_name_plural` to Model View contexts

### ISSUE THREAD

**Issue by carltongibson** [tomchristie/django-vanilla-views#39]
Hey Tom, 

Not sure if you'd go for this but I thought to float it...

I'd like to add `verbose_name` and `verbose_name_plural` keys  for the given model to the default context generated by the model views. 

Given that we already have `object` and `object_list` this would help quick scaffolding with a generic template.

The alternative is a custom template tag, since `_meta` or `__class__` aren't available in the DTL. (I've not found another approach.)

**Comment by tomchristie** [comment]
Baseline is this: Are they included in Django's GCBV codebase? (If so what version? We used to have 100% compat, so that'd be interesting to know)

**Comment by carltongibson** [comment]
i don't think they are. I'll close this. 

Matching Django's behaviour is a nice line to draw. I may do a "Neopolitan" with the additions I'm after.
