### ISSUE TITLE
Add filtering support

### ISSUE THREAD

**Issue by carltongibson** [tomchristie/django-vanilla-views#40]
I'd like to add better support for filtering, similar to DRF. I have in mind Django Filter but a more generic filter backend interface would do too. 

I've found first needing to implement `get_context_data` to pass the filter to the template. No problem here really. 

But then in order to support pagination I have to implement `get_paginator`: 

    def get_paginator(self, queryset, page_size):
        return Paginator(self.filter, page_size)

`filter` here is a property, lazily instantiating the filter instance — I need it there because I still need the filter in the template.

Again, no real problem but it would be nice to just specify a `filter_class`, or `filter_fields` maybe... — in reality I'd guess most cases would merit a `get_filter` implementation, to get the customised filter instance — and have it _Just Work™_

The is kind of relevant to tomchristie/django-rest-framework#2180, where we need to keep the filter backends around in order to pass them to the template. 

I'm happy to do all this if it's acceptable.

**Comment by carltongibson** [comment]
As per #39.

**Comment by ayushin** [comment]
I think adding an overridable filter_queryset() into get would add a lot of flexibility

**Comment by adamchainz** [comment]
Please don't comment on 6 year old issues that were closed with a sensible resolution.
