### ISSUE TITLE
Python 3.4 compatible

### ISSUE THREAD

**Issue by sebastian-code** [tomchristie/django-vanilla-views#42]
Hi.

We were just talking about this through Twitter and you mentioned than it would be nice to have an issue created to include in the documentation the compatibility with Python 3.4

So, well, I just created the issue.

By the way, thanks for the effort, is a great job what you have done here.

**Comment by tomchristie** [comment]
Actually turns out we do have 3.4 in travis, and in the README / docs index.
All that's needed is a docs redeploy.

**Comment by sebastian-code** [comment]
Is there a way I can help with this? I have read the docs and in the docs it's also included the data about compatibility with Python 3.4, so there is no pull request to make, at least than I can see.

And I presume than you need to run the docs redeployment.

If there is something I can do, please let me know.

**Comment by tomchristie** [comment]
Ping me in a few days if it's not already resolved, as a reminder! Thanks.

**Comment by sebastian-code** [comment]
Hey @tomchristie did you did this already? If not, don't forget to, and also to close the issue. And againg, thanks

**Comment by tomchristie** [comment]
Tested versions have been updated.
