### ISSUE TITLE
Inline formsets?

### ISSUE THREAD

**Issue by dfrankow** [tomchristie/django-vanilla-views#43]
I'd love to use this, but I'll look at django-extra-views first because it might let me use inline formsets.

**Comment by dfrankow** [comment]
It would be nice to at least comment on why you closed it.

I assume you don't plan to support anything beyond what's already there, or something like that.

**Comment by tomchristie** [comment]
I wasn't really clear that it was intended as an actionable issue, seemed to just be a casual comment.

Answer: that'd be out of scope for this project, which is simply a replacement for the set of GCBVs that Django provides built-in.

**Comment by dfrankow** [comment]
Thanks for the clarification.
