### ISSUE TITLE
ccbv for vanilla

### ISSUE THREAD

**Issue by alanjds** [tomchristie/django-vanilla-views#46]
Can we have a version of [django-cbv-inspector](https://github.com/refreshoxford/django-cbv-inspector) ? I found django-vanilla-views so nicer, but is yet easier (for me) to check at [ccvb](https://ccbv.co.uk/) than on vanilla docs.

**Comment by tomchristie** [comment]
Nice idea if anyone wants a little side project.
I'd be very happy to link to it prominently from the docs.
