### ISSUE TITLE
Django Forms + CBV for search

### ISSUE THREAD

**Issue by khlumzeemee** [tomchristie/django-vanilla-views#48]
Hi,
I've been trying to combine Forms for a multi-field search page with Class Based View using Django CBV implementation but it turned out to be unpractical and error prone.

Is there an easy way to do that using Vanilla Views? It would be some kind of combination of FormView and ListView. Or is it simply not the way to go for a multiple field search form?

**Comment by tomchristie** [comment]
Probably best to take design questions like this to the django discussion group - reserving the issue tracker here for bug reports. Thanks for your understanding :smile:

**Comment by khlumzeemee** [comment]
Hi Tom,
no problem, could you please redirect me to this django discussion group? Is it the one on Google?

**Comment by tomchristie** [comment]
>  Is it the one on Google groups?

Yes.

**Comment by carltongibson** [comment]
[Django Users Mailing list](https://groups.google.com/forum/#!forum/django-users)
