### ISSUE TITLE
Filtering Foreign Key dropdowns?

### ISSUE THREAD

**Issue by bcoover** [tomchristie/django-vanilla-views#59]
Is there a way to filter the data shown in dropdown lists in forms? I've been trying to use get_form working like this ([link](http://stackoverflow.com/questions/18626221/cbv-createview-limit-foreignkey-based-on-get-initial)), but it does not seem to work with Vanilla, am I missing something?

Basically what I am trying to do is similar to that example. I need to filter the list of options from the foreign key table to only a few. In my case, I want to limit the customer names displayed to only customers that the user is allowed to see.

**Comment by bcoover** [comment]
I think I figured it out, had to put into the super class:

```
def get_form(self, data=None, files=None, **kwargs):
        form = super().get_form(**kwargs)
        form.fields['company'].queryset = Company.objects.filter(id=1)
        return form
```

**Comment by tomchristie** [comment]
> I think I figured it out

Great!
