### ISSUE TITLE
Any idea to load generic views after model migration is done?

### ISSUE THREAD

**Issue by auvipy** [tomchristie/django-vanilla-views#65]
is it good idea to load models in generic views after migration is done? and later views throwing error independently?
https://paste.ubuntu.com/24136369/

**Comment by auvipy** [comment]
http://stackoverflow.com/questions/5775178/getting-the-str-has-no-property-default-manager-on-a-django-app-just-on-sta

**Comment by tomchristie** [comment]
Heya. We use the issue tracker here for bugs and ongoing work rather than usage questions. Probably better to take this question to one of the discussion groups. (Also it's not specific to vanilla views, but to Django generally)

**Comment by auvipy** [comment]
I was wondering If any changes could be possible in vanilla views
