### ISSUE TITLE
Not displaying error when a removed function is being used.

### ISSUE THREAD

**Issue by chessmonster** [tomchristie/django-vanilla-views#74]
Hi Tom,

As stated here http://django-vanilla-views.org/migration/model-views, some of the functions were removed.

I'd like to help improve your library so it will also detect if a user is using the functions that are not really used by vanilla (initial, prefix, get_initial(), get_prefix(), get_form_kwargs(), etc...). And once detected, it will inform that user that he or she is trying to overried a non vanilla library.

Where do I start? I'd like to help because it took me 4 days (LOL) to figure out why overriding some functions were not working.

**Comment by tomchristie** [comment]
Not sure how we'd do that.

**Comment by adamchainz** [comment]
I agree with Tom, I think it shouldn't be up to vanilla views to take on this complexity. I would guess most projects exclusively use vanilla if they are using it. Also triggering a warning for those methods could backfire as a false positive; there's nothing stopping users of vanilla views from making their own methods with the same names that are functional in someway, as opposed to mistakes in usage. Appreciate you lost a lot of time but I think automated testing and other development practices can guard against this. It could happen with any two competing libraries that have different interfaces, there's nothing magical about `django-vanilla-views` against `django` in this respect :)
