### ISSUE TITLE
Django 3.x and Python 3.8.x compatible?

### ISSUE THREAD

**Issue by nuthingman** [tomchristie/django-vanilla-views#88]
Can I use this with Django 3.x?

**Comment by tomchristie** [comment]
We don't have automated tests against Django 3, so can't give you a definitive answer unless someone supplies a pull request adding those.

Having said that, I've no reason to suspect that there's breaking changes against bits of the Django API we integrate with, so I'd suggest trying it and reporting back here.

**Comment by adamchainz** [comment]
#89 fixes, there are some small changes for Django 3.0.
